### PR TITLE
add lon, lat to gridded base write function

### PR DESCRIPTION
**Pull request by sebhahn**

### CODE REVIEW

**Comment by cpaulik** [comment]
Would this not break all the interfaces that do not take a lon and lat keyword?

**Comment by sebhahn** [comment]
no they (should) all have **kwargs, in order to catch kwargs which are not needed in one or the other ioclass

**Comment by cpaulik** [comment]
I'll merge this but I want to wait for a proper release until the issues in the 0.3.6 Milestone are fixed.

**Comment by cpaulik** [comment]
Could you rebase you branch on the latest master to fix the conflicts?

**Pull request closed without merging**
