### PR TITLE
set previous cell flag after reading file to avoid None type returns …

### PR DESCRIPTION
**Pull request by christophreimer**
…of file id.

### CODE REVIEW

**Comment by cpaulik** [comment]
I guess we should do a new release for this bugfix. @sebhahn Could you do this?

**Comment by cpaulik** [comment]
@sebhahn If you add me as an owner in pypi then I can also do releases in the future. Maybe also @christophreimer wants that so that he does not have to wait for a release.

**Comment by cpaulik** [comment]
My pypi username is cpaulik

**Comment by sebhahn** [comment]
I've added you as owner @cpaulik 

If you register at pypi @christophreimer I'll add you too

**Comment by christophreimer** [comment]
I'm now registered at pypi with the username creimer

**Comment by sebhahn** [comment]
ok you're owner now!

**Pull request merged**
